dataset:
  root: C:/test/combined_uav/
  num_workers: 8
  batch_size: 24
  image_size:
  - 512
  - 512
  train_sequences: 70
  val_sequences: 20
  test_sequences: 20
trainer:
  pretrained_path:
  epochs: 50
  optimizer: AdamW
  loss_fn: DiceLoss
  lr: 0.0001
  gpu_id: 0
  scheduler:
    type: ReduceLROnPlateau
    factor: 0.5
    patience: 15
    cooldown: 5
  early_stop:
    patience: 30
    min_delta: 0.001
    mode: min
  checkpoint:
    save_dir: checkpoints/fulldyunet
model:
  name: fulldyunet
  in_channels: 3
  start_out_channels: 64
  num_classes: 1
  num_blocks: 7
  num_padding: 1
  is_upsample: True
